
spring:
  application:
    name: microservice-provider-user
---
spring:
  profiles: port1
server:
  port: 8010
---
spring:
  profiles: port2
server:
  port: 8015
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



